### ISSUE TITLE
Create 'Print' function on each section

### ISSUE THREAD

**Issue by catherineheywood** [alphagov/tech-docs-template#103]
A finding from user research is that people are interested in printing the document as a pdf. However, they would only want to print out selected sections.

**Comment by simonneb** [comment]
For technical documentation, many people prefer to print the docs. Having a small print button at the top of the sections would really help with discoverability.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
