### ISSUE TITLE
Be able to configure the GA tracking event category

### ISSUE THREAD

**Issue by thomasleese** [alphagov/tech-docs-template#112]
The event category is set to "SM Technical Documentation" https://github.com/alphagov/tech-docs-template/blob/ae16d395e7581a0de28aef6ef306b0639e43f482/template/source/javascripts/_analytics.js#L10 but it would be good if this could be configured. Perhaps in the `config/tech-docs.yml` file or perhaps from a `<meta>` tag.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
