### ISSUE TITLE
Back button breaks without in-page-navigation

### ISSUE THREAD

**Issue by kevindew** [alphagov/tech-docs-template#113]
We turned off in-page-navigation because it was causing us problems and found out that without it the back button does not work for navigating between anchors.

**Comment by nickcolley** [comment]
Hello :)

I believe that this is the same issue as https://github.com/alphagov/tech-docs-template/issues/109, please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues) if this is still a problem for you.
