### ISSUE TITLE
Implement support for non-JS users

### ISSUE THREAD

**Issue by paroxp** [alphagov/tech-docs-template#119]
## Why

We've accidentally discovered that this template doesn't render well if the JavaScript is disabled.

Following this blog post:

- [How many people are missing out on JavaScript enhancement?](https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/) by Peter Herlihy

we believe it should be resolved in order to keep up with [Using progressive enhancement](https://www.gov.uk/service-manual/technology/using-progressive-enhancement#dont-assume-users-turn-off-javascript).

**Comment by 36degrees** [comment]
What's the issue with rendering? The content should be just fine, though it will fall back to a non flexbox layout with a non-fixed left hand nav and header.

**Comment by paroxp** [comment]
Hey,

Sorry. That's the issue I'm referring to. It appears you know about this - is that something scheduled or did you decide against fixing it?

![screen shot 2017-11-20 at 12 12 29](https://user-images.githubusercontent.com/2418945/33024428-f5f17f84-ce02-11e7-8dd6-0ed32a1fb925.png)

**Comment by 36degrees** [comment]
Good catch, thanks. I've opened a PR which should improve things a bit.
