### ISSUE TITLE
Last list anchors broken on mobile / tablet viewport

### ISSUE THREAD

**Issue by Nooshu** [alphagov/tech-docs-template#123]
**Note**: Copied this [issue](https://github.com/alphagov/gds-way/issues/99) from the GDS Way.

To reproduce:
- Goto: https://gds-way.cloudapps.digital/#standards
- Shrink the viewport down to approx 760px
- Try clicking on "storing source code" link
- Link not clickable due to following headings negative margin causing an overlap.

![margin-issue](https://user-images.githubusercontent.com/1223960/33012104-d653bcf8-cdd7-11e7-9e8b-f1baf78f580f.png)

Issue caused [here](https://github.com/alphagov/gds-way/blob/bb6a00f98d1bae9f708fe0e99589be818c3171c8/source/stylesheets/modules/_technical-documentation.scss#L54)
````
h3, h4, h5, h6 {
    @include heading-offset($gutter);
  }
````

Proposed fix:

1. Either remove usage of the mixin in this case and add specific styling manually (less padding, no negative margin)
2. Continue to use the mixin but add an override after it's usage

Option 1 seems like the cleanest to me with minimal impact.

**Comment by selfthinker** [comment]
I have used a crude hack in my current project because otherwise people would not be able to get to an important page. I just used a `<br />` before that heading to increase the space on
https://raw.githubusercontent.com/alphagov/accessibility-personas/master/source/setup/index.html.md

**Comment by richardTowers** [comment]
Also affecting https://gds-way.cloudapps.digital/manuals/licensing.html#guidelines-for-repositories-that-are-open-documentation

![image](https://user-images.githubusercontent.com/1696784/52358271-9d283c00-2a2f-11e9-9cdd-e63351207602.png)

**Comment by selfthinker** [comment]
This has now been fixed in https://github.com/alphagov/tech-docs-gem/pull/74.
