### ISSUE TITLE
Update JS/CSS version

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#125]
update it to the latest JS/CSS version

**Comment by pgchamberlin** [comment]
@soupdragon99 can you give any further detail on this? There isn't an obvious interpretation of what JS and CSS versions would be in this context.

**Comment by soupdragon99** [comment]
This was related to and [update for javascript/CSS](https://github.com/alphagov/govuk-developer-docs/pull/536), although this has now been merged.

**Comment by tijmenb** [comment]
Not sure who added that to the spreadsheet, but has been done in GOV.UK's developer docs indeed. Closing!
