### ISSUE TITLE
Navigation - restrict a heading from appearing in the left hand nav

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#127]
We specify the level of headings that appear in the left hand nav of a site through the tech-doc.yaml config file. 

Is it possible to add a feature that allows you to restrict a heading from appearing in the left hand nav? 

For example, if you specify that h1, h2, and h3 headings appear in the nav, but only want certain h3's to appear. Having them all appear would make the left hand nav too long and user-unfriendly.

**Comment by soupdragon99** [comment]
based on requester feedback (with primarily GaaP needs in mind)

**Comment by tijmenb** [comment]
🐝 Issue backlog spring cleaning :cherry_blossom:

I'm not sure if we still want to do this, but feel free to reopen if still needed.
