### ISSUE TITLE
Multi-page format - support multiple pages

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#128]
In recent user testing, the single page format didn't always test well. With further testing, it could be beneficial to support multiple pages. As an example, see the GOV.UK developers or GDS Way implementation of the template.

**Comment by pgchamberlin** [comment]
@soupdragon99 guessing this is about bringing in the work that GOV.UK did? @tijmenb is that something you've been working on?

**Comment by soupdragon99** [comment]
multi-page format  a priority for Registers - Phil already set this up for The GDS Way, how translatable is this to wider audience? PaaS are also want this functionality for their docs.

**Comment by J-Lambo** [comment]
Verify also need this functionality.

**Comment by tijmenb** [comment]
https://github.com/alphagov/tech-docs-template/pull/143 adds some docs to the README of the template to show how to create a separate page. No code changes are needed to support that.
