### ISSUE TITLE
Output - PDF output required for some manuals which can't be published openly

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#129]

**Comment by pgchamberlin** [comment]
@soupdragon99 which manuals are those? It would be good to find out more from whoever needs this.

**Comment by J-Lambo** [comment]
I believe this is a very old request from a former technical writer on Verify. From an old document:
_Some Verify/CTS docs need to be output to PDF and emailed (confidentiality)_

Now I'm on Verify, I don't think this is the case. Either way, I don't think this format is an appropriate solution for closed source documentation.

**Comment by pgchamberlin** [comment]
Ah, OK. Agree this probably isn't the right format for anything closed.
