### ISSUE TITLE
Template - add footer for owner/date information

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#130]
Owner/date information. GOV.UK dev docs have introduced a footer to indicate the owner of the content and when it was last updated - yet to be tested, but nice feature.

**Comment by soupdragon99** [comment]
This offers more reassurance to users that we will update and review content. GOV.UK have sent it up to ping the owner when a review is needed.

**Comment by tijmenb** [comment]
This is a feature of the GOV.UK docs that's probably not easily ported over. If somebody is interested in using it, I could work with them extracting it from the GOV.UK docs.
