### ISSUE TITLE
Navigation - Left-hand nav links sometimes unclear

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#131]
Left-hand nav links sometimes unclear. Difficult to see where you are in the document.

**Comment by soupdragon99** [comment]
Feedback from Registers.

**Comment by soupdragon99** [comment]
I think this could be solved by adding search functionality.

**Comment by J-Lambo** [comment]
I don't think this is something that can be solved by search. Items in the left-hand nav turn to bold as you scroll through, but in user research, users indicated this wasn't clear enough. 

Even if we had search functionality, a user would still need to know what they were reading in relation to the rest of the content. 

The GOV.UK team have already done some work to improve this by highlighting the item in the nav while scrolling. Example here: https://docs.publishing.service.gov.uk/apps/hmrc-manuals-api.html

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
