### ISSUE TITLE
API Explorer - add functionality

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#133]
Research into documentation and formats ongoing, including whether an API explorer would help/hinder register adoption.

**Comment by tijmenb** [comment]
I think an API explorer is probably out of scope for this project. It'll require a fair bit of work, and Middleman is perhaps not the most ideal tech for this.

**Comment by 36degrees** [comment]
We did a _little_ research on this and came to the conclusion that because each separate project (Pay, Notify, etc) would have very specific needs, especially with regards to things like sandboxing, there was little benefit to making it part of the template.

**Comment by tijmenb** [comment]
This is being considered for an outsourced project by GaaP to improve the usability of the template. Stay tuned.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
