### ISSUE TITLE
Compatibility testing

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#136]
Anecdotally we know the template has not been tested thoroughly on Windows

**Comment by pgchamberlin** [comment]
I wonder if we could do some basic testing using something like Browserstack?

**Comment by soupdragon99** [comment]
Has not been tested thoroughly on Windows. Some issues setting up and running documentation using the template. Marian Foley happy to take part in future testing as she has a Windows machine.

**Comment by 36degrees** [comment]
The output of the template was tested thoroughly using Browserstack. Not saying it's perfect, but I'm guessing from @soupdragon99's comment that this is about issues actually 'using' the template and having documentation that caters for Windows users.

**Comment by soupdragon99** [comment]
@pgchamberlin I think the feedback around Windows came out of a training session, I think @36degrees is right about this. I'll follow up with Marian as she initially flagged this up.

**Comment by tijmenb** [comment]
🐝 Issue backlog spring cleaning :cherry_blossom:

I'll close this issue for now. If we receive more concrete issues with developing on Windows we can reopen or open new issues.
