### ISSUE TITLE
Tables render incorrectly

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#138]
Submitted by Marian Foley.

Example added:

"line of text

| This | is | a | table |
| some | words | go | here |

line of text

I also tried with a heading line (tried a line of | --- | and a line of | :--- | but neither worked).

This is a table that renders fine on Whitehall publisher. I was wondering if the dev team could check that it works the same in the tech docs tool.

URL: https://www.gov.uk/guidance/set-up-government-email-services-securely

page in whitehall publisher: https://whitehall-admin.publishing.service.gov.uk/government/admin/detailed-guides/745834"

**Comment by pgchamberlin** [comment]
Examples of this would be welcome

**Comment by soupdragon99** [comment]
A suggestion, not tested.

"We use kramdown, a ""normal"" markdown parser which doesn't support extensions like those which whitehall-publisher provides.  However, you can input tables using standard HTML <table> tags like this:

<table>
  <tr>
    <td>cell one</td>
    <td>cell two</td>
  </tr>
</table>"

**Comment by 36degrees** [comment]
We switched away from kramdown in 3c0947c8cbc3bdfdda2181cc6ea63535f23978a9 because kramdown did not appear to support fenced code blocks.

**Comment by richardTowers** [comment]
In the meantime it's still possible to add tables by writing HTML directly. It's inconvenient, but it works.

**Comment by tijmenb** [comment]
No, markdown tables just work: https://github.com/alphagov/tech-docs-template/pull/141

**Comment by richardTowers** [comment]
Ah, cool, thanks - looks like it's just fussy about whitespace.
