### ISSUE TITLE
Tables don't render properly when followed directly by heading with no characters between

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#139]
Tables do not render properly when they are followed directly by a heading with no characters in between them. The table must have at least one character on a new line between it and the heading that follows in order for the table to work. With this error, the heading breaks as well.

**Comment by pgchamberlin** [comment]
Is this a duplicate of #138 or something different?

**Comment by soupdragon99** [comment]
It looks like this has been resolved:

"workaround tested successfully, we could update this in the doc or start to build a KB on our wiki for example." @jonathanglassman
