### ISSUE TITLE
Headings -  index.html.md.rb & H1 heading

### ISSUE THREAD

**Issue by soupdragon99** [alphagov/tech-docs-template#140]
If your first file in your index.html.md.rb file does not have an H1 heading, it breaks the tool. If you were, for example, to copy some pre-existing markdown files into the documentation folder and they do not have any H1s, and then remove the pre-existing index file from the index.html.md.erb file, then this would happen.

**Comment by soupdragon99** [comment]
not a priority for GaaP - more related to doc architecture than actual bug, poss a guidance issue?

**Comment by tijmenb** [comment]
This is a bug/unintended feature in the https://github.com/alphagov/table_of_contents library that is used by the template.
