### ISSUE TITLE
Question about adding Search function for tech-doc-template

### ISSUE THREAD

**Issue by AntonyBishop** [alphagov/tech-docs-template#150]
Hi,
I'm a Product Manager working over at Ministry of Justice on our Cloud Platform. As part of our new platform we are creating a guide for users based on the tech-docs-template which helps them interact with our platform. 

This first iteration works on the basis that users work through the step by step guidance to build their non-production environment and then build, test and deploy their product (or the Test App). They can then add the resources we have made available e.g. Postgres, secrets, S3 etc.

However, the existing guide doesn't allow the users to search for or skip to specifics. You have to work through the detail or have sufficient context to know where some guidance may exists within the guide. 

We were wondering what the scope is for adding some search facility to allow users to interact with the guidance in a different way to get more value from it.

Grateful for any suggestions. Many thanks.

**Comment by jonathanglassman** [comment]
Hi Antony

Thanks for the message. We are currently developing the tech doc template. One of the priorities is to add a search function to the template so any documentation produced will have an internal search capability. 

It is not known yet what exact form this will take, but please keep an eye on the repo over the next couple of months for any updates on this.

Kind regards

Jon

**Comment by AntonyBishop** [comment]
Thanks Jon. I'll close the issue. Will keep my eyes peeled on the repo.

**Comment by jennyd** [comment]
GOV.UK have [added search functionality](https://github.com/alphagov/govuk-developer-docs/pull/522) to their [technical docs site](https://docs.publishing.service.gov.uk/) using an external service - we could look at doing it that way in this case too @AntonyBishop.

**Comment by AntonyBishop** [comment]
Thanks @jennyd
