### ISSUE TITLE
HTTP with query parameters not rendering properly

### ISSUE THREAD

**Issue by bahmady** [alphagov/tech-docs-template#157]
This is some Markdown:

```
```http
GET /records/KIN/entries/ HTTP/1.1
Host: local-authority-eng.register.gov.uk
Accept: application/json
Authorization: YOUR-API-KEY-HERE
```

Below the bullet point in the image below (as an example) is how it should render, and it does for most of the content:

![image](https://user-images.githubusercontent.com/32935794/42443418-530dbb2a-8365-11e8-8dba-4de9f0bafd0e.png)

... except for similar content which has query parameters (I am assuming this is what's causing the issue), e.g.:

![image](https://user-images.githubusercontent.com/32935794/42443823-7987d2bc-8366-11e8-96f6-39060c843a50.png)

... which has this Markdown:

```
```http
GET /records/local-authority-type/CTY/?page-index=1&page-size=3 HTTP/1.1 
Host: local-authority-eng.register.gov.uk
Accept: application/json
Authorization: YOUR-API-KEY-HERE
```

You can see this live at https://docs.registers.service.gov.uk/

Repo is https://github.com/alphagov/registers-tech-docs

**Comment by tijmenb** [comment]
This doesn't seem to be happening anymore: https://docs.registers.service.gov.uk/api_reference/get_records/#get-records

Perhaps a dependency update fixed this issue. Feel free to reopen if it's still an issue somewhere!
