### ISSUE TITLE
Consider changing the guidance and examples for creating content in this template. Remove the 'documentation' folder and partial includes.

### ISSUE THREAD

**Issue by lewisnyman** [alphagov/tech-docs-template#168]
The recommended method for creating a single-page docs site has been to create one `index.html.md.erb` in the source folder, which is simply a wrapper for the content. The actual content is stored in the documentation folder as .md files, which are pulled into the .html file using [partials.](https://middlemanapp.com/basics/partials/). This makes sense for single-page sites, as it prevents having to manage one bit long page of content.

Since teams have started switching from single page to multipage structures, I've noticed a lot of confusion over the best way to store and reference this content. If you follow the same guidance and best practice as a single page site, then you end up with two content structures you need to manage, one in the main source folder, and another in the documentation folder. It adds unnecessary complexity to the process. 

Jon and I have talked about this every time it's come up, there are several options that we've discussed.

1. Stick to the same guidance for single page and multipage sites that we have now.
2. Create separate guidance and best practices for single page and multipage. Maybe this could be built into the template generator process? What if teams want to switch between single page and multi page?
3. Remove the documentation and partial includes from the example and guidance, assuming that majority of users will create multipage sites. 

This discussion is outside of the scope of project I've worked on, but it's something that needs to be addressed at some point to keep the template easy to use.

**Comment by jonathanglassman** [comment]
Closing as will be solved by https://github.com/alphagov/tdt-documentation/tree/overhaul
