### ISSUE TITLE
Remove `.html` from URL of non-index pages

### ISSUE THREAD

**Issue by theseanything** [alphagov/tech-docs-template#172]
I'm trying to figure out if its possible to customise links to other pages.  Currently `source/errors.html.md.erb` is rendered at the url `/errors.html`.

Ideally we'd like to just use the slug without `.html` extension. i.e. `/errors`. Is this possible?

**Comment by tijmenb** [comment]
Not easily. You'd need to have nginx or something in front of the site.

What does work out of the box is having creating `/source/errors/index.html.md.erb`, which will be served from `/errors/` (but not `/errors`).

**Comment by 36degrees** [comment]
Note however that most (all?) web servers will automatically redirect from `/errors` to `/errors/` – like this, for example:

https://design-system.service.gov.uk/components

**Comment by selfthinker** [comment]
You can use directory indexes as described in https://middlemanapp.com/advanced/pretty-urls/. That will make all pages lose their extension (by changing e.g. `/errors.html` to the page `/errors/index.html` and the link `/errors`).

**Comment by selfthinker** [comment]
I believe my previous comment provides a solution for this? If not, feel free to re-open.
