### ISSUE TITLE
Bad table rendering

### ISSUE THREAD

**Issue by bahmady** [alphagov/tech-docs-template#173]
I can't explain this. 'Normal' (valid) Markdown tables seem to produce this kind of rendering:

![table_bug2](https://user-images.githubusercontent.com/32935794/46481801-14cd2c80-c7ec-11e8-8620-a2dc3783c9f3.png)
![table_bug1](https://user-images.githubusercontent.com/32935794/46481805-172f8680-c7ec-11e8-90c7-a546ec3ddb23.png)

I've been using this "fix" above _and_ below the tables in question:

`<div style="height:1px;font-size:1px;">&nbsp;</div>`

This doesn't seem to affect all tables when it does happen. Updates to the tool seem to affect existing (unaffected) tables randomly— with the emphasis on "seem", I'm sure this is a reason somewhere for this. 

As a workaround I've just applied my "fix" to all my tables.

**Comment by tijmenb** [comment]
@bahmady can you paste in / link to the code that produces this? I think it's the same as https://github.com/alphagov/tech-docs-template/issues/148.

**Comment by bahmady** [comment]
@tijmenb this was from @soupdragon99's tables so tagging him to copy in the code, but yes, I looked at #148 but I discounted it because I don't think it's just after tables. On closer inspection yes, it does look like the same problem.

**Comment by bahmady** [comment]
I'll close this because I think is indeed the same as #148 on closer inspection, but I believe that issue's title is slightly misnamed.
