### ISSUE TITLE
Links before headings not working

### ISSUE THREAD

**Issue by jonathanglassman** [alphagov/tech-docs-template#179]
This issue was raised on GDS Way but appears to affect all tech docs that have upgraded to 1.7.0.

When you have a link just before a heading, the link either doesn't work or is "misaligned" i.e. the cursor doesnt change to a link cursor on the link text, but instead just above it.

**Comment by jonathanglassman** [comment]
For example: https://docs.payments.service.gov.uk/quick_start_guide/#before-you-start

The "payment links" text does not have correctly aligned link functionality.
For example: https://gds-way.cloudapps.digital/manuals/programming-languages/python/linting.html#example-usage
the "Flake8 errors code list" link doesnt work

**Comment by selfthinker** [comment]
This is a duplicate of alphagov/tech-docs-template#123. As far as I know, this was already the case before the latest update?

**Comment by selfthinker** [comment]
This has now been fixed in https://github.com/alphagov/tech-docs-gem/pull/74
