### ISSUE TITLE
Continuous Deployment Process

### ISSUE THREAD

**Issue by jonathanglassman** [alphagov/tech-docs-template#184]
Person from Ministry of Justice :

"FYI, I've put together a continuous deployment process, so that we don't have to commit changes to the 'compiled' html files, after making changes to the source files.

If you're interested, it's more or less documented here:
https://github.com/ministryofjustice/cloud-platform-user-guide/blob/master/.circleci/config.yml

It's quite specific to the way we use TDT, so I don't think it's worth submitting a PR for this, but it might be of interest if/when you get any developers working on it."

**Comment by moj** [comment]
I (@moj) am not the Ministry of Justice.

**Comment by nickcolley** [comment]
Consolidated this into an existing issue: https://github.com/alphagov/tech-docs-gem/issues/146#issuecomment-548795214

Sorry @moj for the mistake tagging you in this!
