### ISSUE TITLE
Table bug

### ISSUE THREAD

**Issue by jonathanglassman** [alphagov/tech-docs-template#190]
To ensure the tables render correctly, you need to add `<div style="height:1px;font-size:1px;">&nbsp;</div>` before and after each table.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).

If you could include some real world examples of where the table renders incorrectly we'll be able to investigate this.
