### ISSUE TITLE
Feature request: addition of optional "print" button on each "page"

### ISSUE THREAD

**Issue by simonneb** [alphagov/tech-docs-template#197]
It might be useful to include an optional "Print this page" button similar to the examples in the [GDS Design SYstem Backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/166). This could be controlled at a universal level in the tech-docs.yaml file.

**Comment by m-green** [comment]
Hi @simonneb - sorry we've also decided to close this issue. We think most technologists use the browser print functionality to print pages. If Design System bring 'print this page' out of their backlog we may revisit this, but for now we don't think we'll be working on this. Thank you for the suggestion though.
