### ISSUE TITLE
Feature request: use Progressive Web App technology for offline support

### ISSUE THREAD

**Issue by simonneb** [alphagov/tech-docs-template#198]
There may be times when there is no internet access and someone may need to use the documentation "offline". Implementing [offline support using Progressive Web App (PWA) technology](https://developers.google.com/web/ilt/pwa/offline-quickstart) would be really useful in this case.

**Comment by m-green** [comment]
Hi @simonneb! Thank you for your suggestion. Unfortunately we don't think we'll be able to prioritise working on offline support - we haven't heard about this need from others, and we think that the way technologists work means they'll almost always be online. So I'll need to close this issue - hope that's ok.
