### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by seanfcarroll** [alphagov/tech-docs-template#203]
From the docs 

> You’re welcome to use the template even if your service isn’t considered part of GOV.UK, but your site or service must not:

> identify itself as being part of GOV.UK
> use the crown or GOV.UK logotype in the header
> use the GDS Transport typeface
> suggest that it’s an official UK government website if it’s not

Does this mean a different font must be used when using this template?

**Comment by m-green** [comment]
Hello Sean - yes that's correct (if you're using the template for something that's not on GOV.UK). However Tech Docs Template pages should automatically use Arial if they can't find the GDS Transport typeface.

Hope that helps - feel free to reopen this issue if you have any more questions.
