### ISSUE TITLE
Ruby and Middleman links

### ISSUE THREAD

**Issue by prateekbuch-no10** [alphagov/tech-docs-template#206]
Hello. The links to installing Ruby and Middlman are broken, returning 404 errors. Any advice? Not keen to install via a search engine in case there are specific versions required

Thanks!

**Comment by m-green** [comment]
Hi @prateekbuch-no10 - sorry for the late reply. The links you mentioned should be fixed now: https://tdt-documentation.london.cloudapps.digital/create_project/get_started/
