### ISSUE TITLE
Add cookie banner functionality

### ISSUE THREAD

**Issue by m-green** [alphagov/tech-docs-template#209]
As Tech Docs Template users need to use a cookie banner to get users' consent to collect Google Analytics data, it'd be useful for the template to have built-in cookie banner functionality to work alongside the [ga tracking id in config](https://tdt-documentation.london.cloudapps.digital/configure_project/global_configuration/#ga-tracking-id).

Should be based on Design System's experimental:

- [cookie banner](https://design-system.service.gov.uk/components/cookie-banner/)
- [cookies page](https://design-system.service.gov.uk/patterns/cookies-page/)

**Comment by jonodrew** [comment]
+1 for this

**Comment by m-green** [comment]
Closing - duplicate of https://github.com/alphagov/tech-docs-gem/pull/227.
