### ISSUE TITLE
Reloading browser ignores any anchors in URL in Chrome

### ISSUE THREAD

**Issue by benh-gds** [alphagov/tech-docs-template#57]
If you navigate to a section so that there's an anchor in the URL e.g. http://localhost:4567/#pushing-an-app-to-cloud-foundry-using-jenkins then refresh the browser, the anchor is ignored and you go to the top of the page, even if the URL is the same.

This does not happen with Safari or Firefox, and it doesn't happen if you go directly to the anchor (e.g. by pasting into browser addressbar or following a link). Low priority but potentially confusing for tech writers or docs readers.

**Comment by 36degrees** [comment]
This was fixed in #67
