### ISSUE TITLE
Width of code blocks

### ISSUE THREAD

**Issue by benh-gds** [alphagov/tech-docs-template#60]
Make sure horizontal scrollbar is always shown on Macs. Investigate button to expand content across the full screen.

**Comment by dashouse** [comment]
I'm seeing the horizontal scrollbar on Safari / Chrome & Firefox. Have you got a screenshot? 

<img width="754" alt="screen shot 2017-01-23 at 15 09 23" src="https://cloud.githubusercontent.com/assets/23356842/22209319/fec4668e-e17d-11e6-8932-84c16679d3e4.png">

**Comment by benh-gds** [comment]
See https://github.com/alphagov/tech-docs-template/issues/63 - there is a MacOS setting to always show scrollbars, but it's off by default.

**Comment by dashouse** [comment]
I do actually have mine set to "Automatically" too. Very strange! Perhaps is actually an OS version thing...

**Comment by benh-gds** [comment]
Hmmm... maybe this issue has been fixed and I'm looking at an old version of the tech docs system? Do you see scrollbars on this: https://paas-tech-docs.cloudapps.digital/#overview ? Even before you start to scroll?

I'm testing on MacOS 10.12.

**Comment by dashouse** [comment]
I am...FYI still on El Capitan 10.11.6

<img width="794" alt="screen shot 2017-01-24 at 15 14 47" src="https://cloud.githubusercontent.com/assets/23356842/22253009/fd8a45fc-e247-11e6-907f-3e2f1b62805b.png">

**Comment by benh-gds** [comment]
Ah, I think somebody else who was on El Capitan was seeing them too. I'm sure there is a way to use CSS to tell Macs to always show the scrollbars as I have run into this problem before.

**Comment by 36degrees** [comment]
There is, but it is not supported by all browsers – specifically, it doesn't affect Firefox. We've got a story to investigate other options.

**Comment by benh-gds** [comment]
If there's a fix that will correct the problem in two of the three main browsers (and doesn't have negative effects on Firefox), maybe we should do that for now?

**Comment by dashouse** [comment]
Potential reason for weirdness... If you have a mouse paired the scrollbars appear by default, they hide if you're using the trackpad only.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
