### ISSUE TITLE
Expanded nav is too long with real content

### ISSUE THREAD

**Issue by benh-gds** [alphagov/tech-docs-template#62]
Need to either: 

1. Make levels shown configurable (for example cuts off at h2)
2. Implement expand/collapse.

**Comment by alexliaume** [comment]
We should look into the accessibility report to see how complicated it is to finalise the expand/collapse nav... link is here: https://docs.google.com/a/digital.cabinet-office.gov.uk/spreadsheets/d/1ddxwgBJHs090hfsWxOU2CQAItdobDPWPhnL6YrZKdqw/edit?usp=sharing

**Comment by 36degrees** [comment]
Fixed by #68
