### ISSUE TITLE
Scrollbar not shown for nav on some Macs

### ISSUE THREAD

**Issue by benh-gds** [alphagov/tech-docs-template#63]
Always show vertical  scrollbar for Mac browsers.

**Comment by dashouse** [comment]
What browser are you missing the scrollbars on? Works for me on Safari / Chrome on Mac...

**Comment by benh-gds** [comment]
There's a MacOS preference in System Preferences > General - if that's set to Always, you will see the scrollbar.  On the other settings, you won't. (Unfortunately I think the default is "Automatically"). To reproduce this, try setting it to "Automatically". Then there won't be a vertical scrollbar shown for the left nav or for wide code blocks that can scroll horizontally.

**Comment by catherineheywood** [comment]
Findings from user research: there's no horizontal scroll bar in Windows (Explorer 11). Our participant wasn't aware of any settings to make it appear so he struggled with trying to copy and paste without being able to see the full code snippet.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
