### ISSUE TITLE
Google analytics isn't available on sections

### ISSUE THREAD

**Issue by catherineheywood** [alphagov/tech-docs-template#64]
It's useful to have reliable Google analytics on the different sections in a document so we can see which bits of content are working and which aren't. Google analytics will pick up clicks in the navigation panel but this won't give a reliable picture if we're working on the assumption that users will scroll through the doc and use the Ctrl+F function to find content.

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
