### ISSUE TITLE
Improve distinction between menu items

### ISSUE THREAD

**Issue by J-Lambo** [alphagov/tech-docs-template#65]
Cosmetic suggestion. 

As well as indenting, it would be great to help distinguish between h2 and h3s in long menus. Perhaps bold or something else? I've attached a pic of the long registers docs menu. 
![screen shot 2016-12-20 at 15 58 14](https://cloud.githubusercontent.com/assets/20108227/21357511/493b7f52-c6cd-11e6-96af-0551a15894d5.png)

**Comment by nickcolley** [comment]
Hello!

I'm doing some tidying up of older issues, if this is something that is still relevant to you please open a new issue on [the tech docs gem repository](https://github.com/alphagov/tech-docs-gem/issues).
