### ISSUE TITLE
Linking to anchors not displayed on ToC doesn't work

### ISSUE THREAD

**Issue by benh-gds** [alphagov/tech-docs-template#82]
Problem:

Trying to follow a link to the anchor of a section that is below the level which is displayed on the left-hand table of contents doesn't work. You are taken to the beginning of the docs instead.

For example:
https://paas-tech-docs.cloudapps.digital/#ip-restrictions should be a valid link. But it's a level 3 header and these docs are configured to show only down to level 2. So following the link doesn't work.

Fix:
Linking to anchors should always work, even if they are not shown on the ToC.

**Comment by 36degrees** [comment]
This has been fixed.
