### ISSUE TITLE
Google indexes heading anchor alt-text

### ISSUE THREAD

**Issue by tijmenb** [alphagov/tech-docs-template#85]
Google apparently runs Javascript and indexes the "Link to here" in the titles.

<img width="688" alt="screen shot 2017-02-07 at 20 41 54" src="https://cloud.githubusercontent.com/assets/233676/22710671/2786cf72-ed76-11e6-9f20-0eb5d70653c1.png">

https://www.google.co.uk/search?q=site%3Adocs.publishing.service.gov.uk

**Comment by 36degrees** [comment]
Working on a fix for this.

Tangentially, this *might* have been avoided if each page in the developer docs had a unique title – at the minute the title for every page appears to be "GOV.UK Documentation" (which, arguably, is even too generic to be the 'overall' title?)

**Comment by tijmenb** [comment]
Thanks @36degrees! Good point about the titles. Incidentally fixed yesterday in https://github.com/alphagov/govuk-developer-docs/pull/40.
