### ISSUE TITLE
header_footer_only doesn't include footer

### ISSUE THREAD

**Issue by tijmenb** [alphagov/tech-docs-template#98]
The [header_and_footer_only template](https://github.com/alphagov/tech-docs-template/blob/master/template/source/layouts/header_footer_only.erb) doesn't actually include the footer. 

Most of the pages on https://docs.publishing.service.gov.uk use that layout, so the footer is only shown on our [guides page](https://docs.publishing.service.gov.uk/guides.html).

**Comment by 36degrees** [comment]
Would #99 work for your use cases?

**Comment by tijmenb** [comment]
Closed via https://github.com/alphagov/tech-docs-template/pull/99 - thanks!
